# Generated by Django 5.1.3 on 2025-10-06 03:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="batch",
            field=models.CharField(
                choices=[
                    ("Day Batch", "Day Batch"),
                    ("Sunday Batch", "Sunday Batch"),
                    ("Overseer (Sunday Only)", "Overseer (Sunday Only)"),
                    ("Night Batch", "Night Batch"),
                ],
                default="Day Batch",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="date_joined",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="student",
            name="fees_paid",
            field=models.BooleanField(default=False),
        ),
    ]
