# Generated by Django 5.1.3 on 2025-10-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0003_student_batch_student_date_joined_student_fees_paid"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch",
                    models.CharField(
                        choices=[
                            ("Day Batch", "Day Batch"),
                            ("Sunday Batch", "Sunday Batch"),
                            ("Overseer (Sunday Only)", "Overseer (Sunday Only)"),
                            ("Night Batch", "Night Batch"),
                        ],
                        max_length=50,
                    ),
                ),
                ("topic", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "room_or_link",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
            ],
        ),
    ]
