# Generated by Django 5.1.3 on 2025-10-06 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0004_classschedule_event_exam"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("date", models.DateField(default=datetime.date.today)),
                ("time", models.TimeField(default=datetime.time(10, 0))),
            ],
        ),
        migrations.DeleteModel(
            name="Exam",
        ),
        migrations.AlterField(
            model_name="classschedule",
            name="batch",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="classschedule",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="classschedule",
            name="room_or_link",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="classschedule",
            name="time",
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
